"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-01-01 00:00:00

Hand-written (not autogenerated) so it matches docs/database.md verbatim --
that document is the schema of record for this project.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


DDL_UP = """
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "user" (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    role            TEXT NOT NULL CHECK (role IN ('ADMIN', 'ADVERTISER', 'PUBLISHER')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE advertiser (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id   UUID REFERENCES "user"(id),
    name            TEXT NOT NULL,
    budget          NUMERIC(12, 4) NOT NULL CHECK (budget >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campaign (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    advertiser_id       UUID NOT NULL REFERENCES advertiser(id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    daily_budget        NUMERIC(12, 4) NOT NULL CHECK (daily_budget >= 0),
    remaining_budget    NUMERIC(12, 4) NOT NULL CHECK (remaining_budget >= 0),
    bid_floor           NUMERIC(10, 4) NOT NULL DEFAULT 0,
    target_countries    TEXT[] NOT NULL DEFAULT '{}',
    target_devices      TEXT[] NOT NULL DEFAULT '{}',
    status              TEXT NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED', 'ENDED')) DEFAULT 'ACTIVE',
    start_time          TIMESTAMPTZ NOT NULL,
    end_time            TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (end_time > start_time)
);

CREATE TABLE creative (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id     UUID NOT NULL REFERENCES campaign(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    image_url       TEXT NOT NULL,
    landing_url     TEXT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED')) DEFAULT 'ACTIVE'
);

CREATE TABLE publisher (
    id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name    TEXT NOT NULL
);

CREATE TABLE ad_slot (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    publisher_id    UUID NOT NULL REFERENCES publisher(id) ON DELETE CASCADE,
    placement       TEXT NOT NULL,
    width           INTEGER NOT NULL,
    height          INTEGER NOT NULL,
    floor_price     NUMERIC(10, 4) NOT NULL DEFAULT 0
);

CREATE TABLE dsp (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL UNIQUE,
    endpoint        TEXT NOT NULL,
    timeout_ms      INTEGER NOT NULL DEFAULT 100,
    status          TEXT NOT NULL CHECK (status IN ('ACTIVE', 'DISABLED')) DEFAULT 'ACTIVE'
);

CREATE TABLE bid (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id          UUID NOT NULL,
    dsp_id              UUID NOT NULL REFERENCES dsp(id),
    campaign_id         UUID NOT NULL REFERENCES campaign(id),
    amount              NUMERIC(10, 4) NOT NULL CHECK (amount >= 0),
    response_time_ms    INTEGER,
    status              TEXT NOT NULL CHECK (
                            status IN ('VALID', 'TIMEOUT', 'INVALID', 'BELOW_FLOOR', 'BUDGET_EXCEEDED', 'WON', 'LOST')
                        ),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auction (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id      TEXT NOT NULL UNIQUE,
    ad_slot_id      UUID NOT NULL REFERENCES ad_slot(id),
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at    TIMESTAMPTZ,
    duration_ms     INTEGER,
    status          TEXT NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'NO_BID', 'FAILED')) DEFAULT 'PENDING',
    winning_bid_id  UUID REFERENCES bid(id)
);

ALTER TABLE bid
    ADD CONSTRAINT fk_bid_auction
    FOREIGN KEY (auction_id) REFERENCES auction(id) ON DELETE CASCADE;

CREATE TABLE impression (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auction_id      UUID NOT NULL REFERENCES auction(id),
    campaign_id     UUID NOT NULL REFERENCES campaign(id),
    "timestamp"     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE click (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    impression_id   UUID NOT NULL REFERENCES impression(id) ON DELETE CASCADE,
    "timestamp"     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_campaign_status         ON campaign(status);
CREATE INDEX idx_campaign_advertiser_id  ON campaign(advertiser_id);
CREATE INDEX idx_campaign_start_end      ON campaign(start_time, end_time);
CREATE INDEX idx_bid_auction_id          ON bid(auction_id);
CREATE INDEX idx_bid_dsp_id              ON bid(dsp_id);
CREATE INDEX idx_auction_created_at      ON auction(started_at);
CREATE INDEX idx_auction_status          ON auction(status);
CREATE INDEX idx_impression_campaign_id  ON impression(campaign_id);
CREATE INDEX idx_impression_timestamp    ON impression("timestamp");
"""

DDL_DOWN = """
DROP TABLE IF EXISTS click;
DROP TABLE IF EXISTS impression;
DROP TABLE IF EXISTS bid;
DROP TABLE IF EXISTS auction;
DROP TABLE IF EXISTS dsp;
DROP TABLE IF EXISTS ad_slot;
DROP TABLE IF EXISTS publisher;
DROP TABLE IF EXISTS creative;
DROP TABLE IF EXISTS campaign;
DROP TABLE IF EXISTS advertiser;
DROP TABLE IF EXISTS "user";
"""


def _strip_sql_comments(ddl: str) -> str:
    """Drop whole-line SQL comments before splitting on ';'. Necessary
    because a semicolon inside a comment's prose would otherwise be
    mistaken for a statement boundary by the split in _execute_statements."""
    return "\n".join(
        line for line in ddl.splitlines() if not line.strip().startswith("--")
    )


def _execute_statements(ddl: str) -> None:
    """asyncpg (unlike psycopg2) refuses to run multiple SQL statements in a
    single prepared statement/execute() call, and SQLAlchemy's asyncpg
    dialect has a separate quirk where op.execute() on plain DDL text can
    trip its RETURNING-detection regex, raising a confusing
    'expected string or bytes-like object, got NoneType' error. Going
    through the raw connection's exec_driver_sql avoids both issues.

    NOTE: this helper is duplicated (not imported) in each migration file
    in this directory, deliberately -- `alembic` here is both this
    project's script-location folder name AND the installed pip package
    name, so `from alembic.<local_module> import ...` silently resolves to
    the real installed package instead of this folder and fails at import
    time. A shared helper module would need to live outside the `alembic/`
    directory (e.g. `app/core/`) to be importable; it's kept inline here
    instead since these migrations are one-time, frozen historical record
    and unlikely to need further changes.
    """
    connection = op.get_bind()
    cleaned = _strip_sql_comments(ddl)
    for statement in cleaned.split(";"):
        statement = statement.strip()
        if statement:
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(DDL_UP)


def downgrade() -> None:
    _execute_statements(DDL_DOWN)