from app.core.config import get_settings

settings = get_settings()

AUCTION_EVENTS = settings.KAFKA_TOPIC_AUCTION_EVENTS
BID_EVENTS = settings.KAFKA_TOPIC_BID_EVENTS
IMPRESSION_EVENTS = settings.KAFKA_TOPIC_IMPRESSION_EVENTS
CLICK_EVENTS = settings.KAFKA_TOPIC_CLICK_EVENTS
CAMPAIGN_EVENTS = settings.KAFKA_TOPIC_CAMPAIGN_EVENTS
DEAD_LETTER = settings.KAFKA_TOPIC_DEAD_LETTER

ALL_TOPICS = [
    AUCTION_EVENTS,
    BID_EVENTS,
    IMPRESSION_EVENTS,
    CLICK_EVENTS,
    CAMPAIGN_EVENTS,
    DEAD_LETTER,
]